# Generated by Django 3.0.2 on 2020-01-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0002_remove_article_for_adult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
